### PR TITLE
Fix #70 - cancel an expired payment

### LINKED ISSUE #70: [Cancel] - cannot cancel an order with an expired Checkout Session
:vulcan_salute:  
we facing to an issue for cancelling former order (presume missing cron for `sylius:cancel-unpaid-orders` cmd), when admin click on cancel btn from order detail page, we hit a 500 error 

```text
Handling "FluxSE\SyliusPayumStripePlugin\Command\CancelPayment" failed: Only Checkout Sessions with a status in ["open"] can be expired. This Checkout Session has a status of `expired`.
```

and this is the same thing when we run cli cmd `bin/console sylius:cancel-unpaid-orders -vv` 

```bash
....
 In ApiErrorException.php line 38:
                                                                                                                     
  [Stripe\Exception\InvalidRequestException]                                                                         
  Only Checkout Sessions with a status in ["open"] can be expired. This Checkout Session has a status of `expired`.  
                                                                                                                     

Exception trace:
  at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php:38
 Stripe\Exception\ApiErrorException::factory() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/Exception/InvalidRequestException.php:35
 Stripe\Exception\InvalidRequestException::factory() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/ApiRequestor.php:213
 Stripe\ApiRequestor::_specificAPIError() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/ApiRequestor.php:175
 Stripe\ApiRequestor->handleErrorResponse() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/ApiRequestor.php:556
 Stripe\ApiRequestor->_interpretResponse() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/ApiRequestor.php:124
 Stripe\ApiRequestor->request() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/ApiOperations/Request.php:78
 Stripe\ApiResource::_staticRequest() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/ApiOperations/Request.php:42
 Stripe\ApiResource->_request() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/stripe/stripe-php/lib/Checkout/Session.php:130
 Stripe\Checkout\Session->expire() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/flux-se/payum-stripe/src/Action/Api/Resource/ExpireSessionAction.php:42
 FluxSE\PayumStripe\Action\Api\Resource\ExpireSessionAction->expireSession() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/flux-se/payum-stripe/src/Action/Api/Resource/ExpireSessionAction.php:35
 FluxSE\PayumStripe\Action\Api\Resource\ExpireSessionAction->retrieveApiResource() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/flux-se/payum-stripe/src/Action/Api/Resource/AbstractRetrieveAction.php:25
 FluxSE\PayumStripe\Action\Api\Resource\AbstractRetrieveAction->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/payum/payum/src/Payum/Core/Gateway.php:107
 Payum\Core\Gateway->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/flux-se/payum-stripe/src/Action/StripeCheckoutSession/CancelAction.php:37
 FluxSE\PayumStripe\Action\StripeCheckoutSession\CancelAction->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/payum/payum/src/Payum/Core/Gateway.php:107
 Payum\Core\Gateway->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Action/ExecuteSameRequestWithPaymentDetailsAction.php:38
 Sylius\Bundle\PayumBundle\Action\ExecuteSameRequestWithPaymentDetailsAction->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/payum/payum/src/Payum/Core/Gateway.php:107
 Payum\Core\Gateway->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/payum/payum/src/Payum/Core/Action/ExecuteSameRequestWithModelDetailsAction.php:36
 Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/payum/payum/src/Payum/Core/Gateway.php:107
 Payum\Core\Gateway->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/flux-se/sylius-payum-stripe-plugin/src/CommandHandler/CancelPaymentHandler.php:54
 FluxSE\SyliusPayumStripePlugin\CommandHandler\CancelPaymentHandler->__invoke() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:152
 Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->callHandler() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:91
 Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php:71
 Symfony\Component\Messenger\Middleware\SendMessageMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/doctrine-bridge/Messenger/DoctrineTransactionMiddleware.php:31
 Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware->handleForManager() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/doctrine-bridge/Messenger/AbstractDoctrineMiddleware.php:45
 Symfony\Bridge\Doctrine\Messenger\AbstractDoctrineMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/ValidationMiddleware.php:45
 Symfony\Component\Messenger\Middleware\ValidationMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:34
 Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php:68
 Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php:41
 Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php:37
 Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/Middleware/TraceableMiddleware.php:40
 Symfony\Component\Messenger\Middleware\TraceableMiddleware->handle() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/MessageBus.php:70
 Symfony\Component\Messenger\MessageBus->dispatch() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/messenger/TraceableMessageBus.php:38
 Symfony\Component\Messenger\TraceableMessageBus->dispatch() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/flux-se/sylius-payum-stripe-plugin/src/StateMachine/CancelOrderProcessor.php:34
 FluxSE\SyliusPayumStripePlugin\StateMachine\CancelOrderProcessor->__invoke() at n/a:n/a
 call_user_func_array() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/Callback/Callback.php:75
 SM\Callback\Callback->call() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine-bundle/Callback/ContainerAwareCallback.php:55
 winzou\Bundle\StateMachineBundle\Callback\ContainerAwareCallback->call() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/Callback/Callback.php:84
 SM\Callback\Callback->__invoke() at n/a:n/a
 call_user_func() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/StateMachine/StateMachine.php:217
 SM\StateMachine\StateMachine->callCallbacks() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/StateMachine/StateMachine.php:135
 SM\StateMachine\StateMachine->apply() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/Callback/CascadeTransitionCallback.php:58
 SM\Callback\CascadeTransitionCallback->apply() at n/a:n/a
 call_user_func_array() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/Callback/Callback.php:75
 SM\Callback\Callback->call() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine-bundle/Callback/ContainerAwareCallback.php:55
 winzou\Bundle\StateMachineBundle\Callback\ContainerAwareCallback->call() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/Callback/Callback.php:84
 SM\Callback\Callback->__invoke() at n/a:n/a
 call_user_func() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/StateMachine/StateMachine.php:217
 SM\StateMachine\StateMachine->callCallbacks() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/winzou/state-machine/src/SM/StateMachine/StateMachine.php:135
 SM\StateMachine\StateMachine->apply() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/sylius/sylius/src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdater.php:64
 Sylius\Component\Core\Updater\UnpaidOrdersStateUpdater->cancelOrder() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/sylius/sylius/src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdater.php:49
 Sylius\Component\Core\Updater\UnpaidOrdersStateUpdater->cancel() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php:45
 Sylius\Bundle\CoreBundle\Command\CancelUnpaidOrdersCommand->execute() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/framework-bundle/Console/Application.php:126
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /warehouse/sylius/master-forks/s3cr3t-proj3ct/bin/console:38

sylius:cancel-unpaid-orders
```

a potential solution will be to add an additional check on `FluxSE\SyliusPayumStripePlugin\CommandHandler\CancelPaymentHandler`  to compare field `expired_at` (in payment detail) to current timestamp and pass if payment already expired 

or there is a better solution ?

### PR DESCRIPTION
**Pull request by cbastienbaron**

### CODE REVIEW

File: src/CommandHandler/CancelPaymentHandler.php [hunk 1]
```diff
@@ -39,6 +39,10 @@ public function __invoke(CancelPayment $command): void
             return;
         }
 
+        if(array_key_exists('expires_at', $payment->getDetails()) && $payment->getDetails()['expires_at'] < time()) {
```
Comment (Prometee) [inline src/CommandHandler/CancelPaymentHandler.php:42]: There is a service to get the current time in Symfony, can you use it instead of using `time()` function ? https://symfony.com/doc/current/components/clock.html#nativeclock

Using it allows for more control over the current date.

**Review by Prometee — CHANGES_REQUESTED** [review]

File: src/CommandHandler/CancelPaymentHandler.php (hunk 1 above)
Comment (Prometee) [reply src/CommandHandler/CancelPaymentHandler.php:42]:
```suggestion
        $details = $payment->getDetails();
        if(!isset($details['expires_at'])) {
            return;
        }
        
        if($details['expires_at'] < $this->clock->now()->getTimestamp()) {
```

**Comment by Prometee** [comment]
@cbastienbaron Sorry I did not check it but the `symfony/clock` is not available on Symfony 5.4 making it not usable in our case, but there is a similar service created by Sylius to do the same thing: `Sylius\Calendar\Provider\DateTimeProviderInterface`

**Comment by cbastienbaron** [comment]
hey @Prometee  :vulcan_salute: 

there is another thing can i do ?

**Comment by Prometee** [comment]
Hello @cbastienbaron !

Sorry about the delay...

It seems that the clock service is not available on Sf 5.4 and PHP 7.4, since this code will have to remain compatible with those deps, I think you were right at the first try where you set a simple DateTime instance to check the date, this is not ideal but we can't do much more.

Are you able to do so? Then if the static build is ok I will merge your PR.

**Review by Prometee — APPROVED** [review]

**Comment by Prometee** [comment]
Thank you @cbastienbaron 🎉
